
/* DHCP协议栈配置 */
#define CONFIG_BOOTP_SUBNETMASK
#define CONFIG_BOOTP_GATEWAY
#define CONFIG_BOOTP_DNS
#define CONFIG_BOOTP_HOSTNAME
#define CONFIG_BOOTP_BOOTPATH
#define CONFIG_BOOTP_PXE
#define CONFIG_NET_RETRY_COUNT  5
#define CONFIG_BOOTP_TIMEOUT    5000
